name: C Tests with Valgrind

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc make valgrind

    - name: Build tests
      run: make test_hashmap

    - name: Run tests normally
      run: ./test_hashmap

    - name: Run tests with Valgrind
      run: |
        valgrind --leak-check=full --error-exitcode=1 ./test_hashmap

    - name: Build More tests
      run: make all
    
    - name: Run tests with Valgrind
      run: make valgrind_test